# 가중치

In [1]:
from sklearn.preprocessing import (LabelEncoder, LabelBinarizer, RobustScaler)

In [2]:
from sklearn.model_selection import (train_test_split, cross_val_score, StratifiedKFold ,GridSearchCV)

In [3]:
from sklearn.metrics import (accuracy_score, roc_auc_score, classification_report, confusion_matrix)

In [4]:
from sklearn.tree import DecisionTreeClassifier
from graphviz import Source
from sklearn.tree import export_graphviz

In [5]:
from sklearn.ensemble import GradientBoostingClassifier
import time
import warnings

warnings.filterwarnings('ignore')

In [6]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [7]:
from sklearn.preprocessing import (LabelEncoder, LabelBinarizer, RobustScaler)

In [8]:
from sklearn.model_selection import (train_test_split, cross_val_score, StratifiedKFold ,GridSearchCV)

In [9]:
from sklearn.metrics import (accuracy_score, roc_auc_score, classification_report, confusion_matrix)

In [10]:
from sklearn.tree import DecisionTreeClassifier
from graphviz import Source
from sklearn.tree import export_graphviz

In [11]:
from sklearn.ensemble import GradientBoostingClassifier
import time
import warnings

warnings.filterwarnings('ignore')

In [12]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# ada, gbc, xgb, lgbm 모델 함수

In [13]:
# ada, gbc, xgb, lgbm

In [14]:
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [15]:
ada = AdaBoostClassifier(random_state=13)
gbc = GradientBoostingClassifier(random_state=13)
xgb = XGBClassifier(random_state=13)
lgbm = LGBMClassifier(random_state=13)

In [16]:
models = [ada, gbc, xgb, lgbm]
model_names = ['Ada', 'GBC', 'XGB', 'LGBM']

In [17]:
from sklearn.metrics import (accuracy_score, precision_score, recall_score, 
                             f1_score, roc_auc_score, confusion_matrix)

def get_score(y_test, pred):
    acc = accuracy_score(y_test, pred)
    pre = precision_score(y_test, pred)
    rec = recall_score(y_test, pred)
    f1 = f1_score(y_test, pred)
    auc = roc_auc_score(y_test, pred)
   
    return acc, auc, pre, rec, f1

def print_score(y_test, pred, confusion=False, score=False):
    acc, auc, pre, rec, f1 = get_score(y_test, pred)
    con = confusion_matrix(y_test, pred)
    if confusion==True:
        print('confusion matrix')
        print(con)
        print('='*20)
    
    if score==True:
        print('Accuracy: {0:.4f}, AUC: {1:.4f}'.format(acc, auc))
        print('Recall: {0:.4f}, f1_score: {1:.4f}, precision: {2:.4f}'.format(rec, f1, pre))

In [18]:
def fit_model(model, X_train, X_test, y_train, y_test):
#     skfold = StratifiedKFold(n_splits=5)
#     cv_scores = []
#     for score in ['accuracy', 'roc_auc']:    
#         score_cv = cross_val_score(model, X_train, y_train, scoring=score, cv=5)
#         cv_scores.append(round(score_cv.mean(), 4))
    model.fit(X_train, y_train)
    y_pre_tr = model.predict(X_train)
    y_pre_test = model.predict(X_test)
    
    return get_score(y_test, y_pre_test)

def models_score_df(models, model_names, X_train, X_test, y_train, y_test):
    cols_names = ['accuracy', 'AUC', 'precision', 'recall', 'f1']
    datas = []
    for model in models:
        datas.append(fit_model(model, X_train, X_test, y_train, y_test))
     
    return pd.DataFrame(datas, columns=cols_names, index=model_names)

## train test 불러오기

In [19]:
X_test = pd.read_csv('../MACH_data/X_test_data_without_0feature.csv' )
X_test

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,orientation_Other,race_Arab,race_Asian,race_Black,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married
0,2.0,17.0,5.0,2.0,20.0,11.0,5.0,1.0,30.0,3.0,...,0,0,0,0,0,0,1,0,1,0
1,1.0,15.0,5.0,2.0,4.0,6.0,2.0,9.0,5.0,5.0,...,0,0,0,0,0,0,1,0,1,0
2,1.0,9.0,45.0,5.0,18.0,13.0,1.0,5.0,30.0,5.0,...,0,0,0,0,0,0,1,0,1,0
3,5.0,19.0,7.0,2.0,6.0,11.0,2.0,1.0,10.0,1.0,...,0,0,0,0,0,0,1,0,1,0
4,5.0,20.0,2.0,4.0,8.0,2.0,2.0,1.0,8.0,2.0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10939,5.0,3.0,9.0,4.0,13.0,6.0,3.0,6.0,15.0,4.0,...,0,0,0,0,0,0,1,0,1,0
10940,1.0,3.0,11.0,1.0,4.0,7.0,3.0,15.0,4.0,5.0,...,0,0,0,0,0,0,1,0,0,1
10941,4.0,9.0,8.0,5.0,16.0,5.0,1.0,1.0,5.0,5.0,...,0,0,0,0,0,0,1,0,1,0
10942,4.0,1.0,3.0,4.0,18.0,5.0,3.0,4.0,9.0,2.0,...,0,0,0,0,0,0,1,1,0,0
10943,5.0,11.0,9.0,5.0,17.0,11.0,2.0,8.0,8.0,1.0,...,0,1,0,0,0,0,0,1,0,0

In [20]:
X_train = pd.read_csv('../MACH_data/X_train_data_without_0feature.csv' )
X_train

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,orientation_Other,race_Arab,race_Asian,race_Black,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married
0,5.0,11.0,3.0,5.0,18.0,4.0,1.0,14.0,4.0,1.0,...,0,0,0,0,0,0,1,0,1,0
1,3.0,19.0,8.0,2.0,8.0,6.0,5.0,7.0,5.0,3.0,...,0,0,0,0,0,0,1,0,1,0
2,5.0,7.0,5.0,4.0,18.0,3.0,5.0,11.0,1.0,4.0,...,0,0,0,0,0,0,1,0,1,0
3,2.0,17.0,7.0,1.0,12.0,4.0,4.0,14.0,4.0,4.0,...,0,0,1,0,0,0,0,0,1,0
4,5.0,13.0,6.0,5.0,20.0,5.0,2.0,4.0,6.0,1.0,...,0,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43769,4.0,19.0,6.0,5.0,3.0,19.0,3.0,9.0,10.0,3.0,...,0,0,1,0,0,0,0,0,1,0
43770,5.0,3.0,11.0,5.0,11.0,7.0,5.0,16.0,7.0,3.0,...,0,0,0,1,0,0,0,0,1,0
43771,4.0,7.0,11.0,3.0,12.0,6.0,2.0,13.0,82.0,2.0,...,0,0,0,0,0,0,1,0,1,0
43772,4.0,17.0,5.0,5.0,19.0,3.0,5.0,13.0,13.0,4.0,...,0,0,0,0,0,0,1,0,1,0
43773,1.0,10.0,11.0,1.0,3.0,5.0,3.0,14.0,5.0,5.0,...,0,0,0,0,0,0,1,0,0,1

In [21]:
y_test = pd.read_csv('../MACH_data/Y_test_data_without_0feature.csv' )
y_test

       voted
0          0
1          0
2          1
3          1
4          0
...      ...
10939      1
10940      1
10941      0
10942      0
10943      1

[10944 rows x 1 columns]

In [22]:
y_train = pd.read_csv('../MACH_data/Y_train_data_without_0feature.csv' )
y_train

       voted
0          1
1          1
2          0
3          0
4          1
...      ...
43769      1
43770      0
43771      0
43772      0
43773      0

[43774 rows x 1 columns]

In [23]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((43774, 221), (10944, 221), (43774, 1), (10944, 1))

In [24]:
df_tr = pd.concat([X_train, y_train], axis=1)
df_tr

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,race_Arab,race_Asian,race_Black,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married,voted
0,5.0,11.0,3.0,5.0,18.0,4.0,1.0,14.0,4.0,1.0,...,0,0,0,0,0,1,0,1,0,1
1,3.0,19.0,8.0,2.0,8.0,6.0,5.0,7.0,5.0,3.0,...,0,0,0,0,0,1,0,1,0,1
2,5.0,7.0,5.0,4.0,18.0,3.0,5.0,11.0,1.0,4.0,...,0,0,0,0,0,1,0,1,0,0
3,2.0,17.0,7.0,1.0,12.0,4.0,4.0,14.0,4.0,4.0,...,0,1,0,0,0,0,0,1,0,0
4,5.0,13.0,6.0,5.0,20.0,5.0,2.0,4.0,6.0,1.0,...,0,0,0,0,0,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43769,4.0,19.0,6.0,5.0,3.0,19.0,3.0,9.0,10.0,3.0,...,0,1,0,0,0,0,0,1,0,1
43770,5.0,3.0,11.0,5.0,11.0,7.0,5.0,16.0,7.0,3.0,...,0,0,1,0,0,0,0,1,0,0
43771,4.0,7.0,11.0,3.0,12.0,6.0,2.0,13.0,82.0,2.0,...,0,0,0,0,0,1,0,1,0,0
43772,4.0,17.0,5.0,5.0,19.0,3.0,5.0,13.0,13.0,4.0,...,0,0,0,0,0,1,0,1,0,0
43773,1.0,10.0,11.0,1.0,3.0,5.0,3.0,14.0,5.0,5.0,...,0,0,0,0,0,1,0,0,1,0

In [25]:
df_te = X_test
df_te

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,orientation_Other,race_Arab,race_Asian,race_Black,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married
0,2.0,17.0,5.0,2.0,20.0,11.0,5.0,1.0,30.0,3.0,...,0,0,0,0,0,0,1,0,1,0
1,1.0,15.0,5.0,2.0,4.0,6.0,2.0,9.0,5.0,5.0,...,0,0,0,0,0,0,1,0,1,0
2,1.0,9.0,45.0,5.0,18.0,13.0,1.0,5.0,30.0,5.0,...,0,0,0,0,0,0,1,0,1,0
3,5.0,19.0,7.0,2.0,6.0,11.0,2.0,1.0,10.0,1.0,...,0,0,0,0,0,0,1,0,1,0
4,5.0,20.0,2.0,4.0,8.0,2.0,2.0,1.0,8.0,2.0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10939,5.0,3.0,9.0,4.0,13.0,6.0,3.0,6.0,15.0,4.0,...,0,0,0,0,0,0,1,0,1,0
10940,1.0,3.0,11.0,1.0,4.0,7.0,3.0,15.0,4.0,5.0,...,0,0,0,0,0,0,1,0,0,1
10941,4.0,9.0,8.0,5.0,16.0,5.0,1.0,1.0,5.0,5.0,...,0,0,0,0,0,0,1,0,1,0
10942,4.0,1.0,3.0,4.0,18.0,5.0,3.0,4.0,9.0,2.0,...,0,0,0,0,0,0,1,1,0,0
10943,5.0,11.0,9.0,5.0,17.0,11.0,2.0,8.0,8.0,1.0,...,0,1,0,0,0,0,0,1,0,0

### weight 계산

In [26]:
df_tr[["voted", "score"]].groupby("score").count()

       voted
score
20.0       5
21.0       2
22.0       5
23.0       6
24.0      23
...      ...
96.0     379
97.0     173
98.0     141
99.0      82
100.0    253

[81 rows x 1 columns]

In [27]:
weight_all_tr = df_tr[["voted", "score"]].groupby("score").count()

In [28]:
weight_yes_tr = df_tr[["voted", "score"]].groupby("score").sum()

In [29]:
weight_no_tr = weight_all_tr - weight_yes_tr

In [30]:
df_weight_tr = (weight_yes_tr - weight_no_tr)/ weight_all_tr

### train test merge

In [31]:
df1_tr = pd.merge(left=df_tr, right=df_weight_tr, how="left", right_index=True, left_on="score")
df1_tr

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,race_Asian,race_Black,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married,voted_x,voted_y
0,5.0,11.0,3.0,5.0,18.0,4.0,1.0,14.0,4.0,1.0,...,0,0,0,0,1,0,1,0,1,-0.041009
1,3.0,19.0,8.0,2.0,8.0,6.0,5.0,7.0,5.0,3.0,...,0,0,0,0,1,0,1,0,1,0.158416
2,5.0,7.0,5.0,4.0,18.0,3.0,5.0,11.0,1.0,4.0,...,0,0,0,0,1,0,1,0,0,0.027542
3,2.0,17.0,7.0,1.0,12.0,4.0,4.0,14.0,4.0,4.0,...,1,0,0,0,0,0,1,0,0,0.079208
4,5.0,13.0,6.0,5.0,20.0,5.0,2.0,4.0,6.0,1.0,...,0,0,0,0,1,0,1,0,1,-0.047154
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43769,4.0,19.0,6.0,5.0,3.0,19.0,3.0,9.0,10.0,3.0,...,1,0,0,0,0,0,1,0,1,0.101053
43770,5.0,3.0,11.0,5.0,11.0,7.0,5.0,16.0,7.0,3.0,...,0,1,0,0,0,0,1,0,0,0.081420
43771,4.0,7.0,11.0,3.0,12.0,6.0,2.0,13.0,82.0,2.0,...,0,0,0,0,1,0,1,0,0,-0.029508
43772,4.0,17.0,5.0,5.0,19.0,3.0,5.0,13.0,13.0,4.0,...,0,0,0,0,1,0,1,0,0,-0.004202
43773,1.0,10.0,11.0,1.0,3.0,5.0,3.0,14.0,5.0,5.0,...,0,0,0,0,1,0,0,1,0,0.214876

In [32]:
df1_te = pd.merge(left=df_te, right=df_weight_tr, how="left", right_index=True, left_on="score")
df1_te

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,race_Arab,race_Asian,race_Black,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married,voted
0,2.0,17.0,5.0,2.0,20.0,11.0,5.0,1.0,30.0,3.0,...,0,0,0,0,0,1,0,1,0,0.011790
1,1.0,15.0,5.0,2.0,4.0,6.0,2.0,9.0,5.0,5.0,...,0,0,0,0,0,1,0,1,0,0.079727
2,1.0,9.0,45.0,5.0,18.0,13.0,1.0,5.0,30.0,5.0,...,0,0,0,0,0,1,0,1,0,0.114504
3,5.0,19.0,7.0,2.0,6.0,11.0,2.0,1.0,10.0,1.0,...,0,0,0,0,0,1,0,1,0,0.025845
4,5.0,20.0,2.0,4.0,8.0,2.0,2.0,1.0,8.0,2.0,...,0,1,0,0,0,0,0,1,0,-0.019512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10939,5.0,3.0,9.0,4.0,13.0,6.0,3.0,6.0,15.0,4.0,...,0,0,0,0,0,1,0,1,0,-0.002222
10940,1.0,3.0,11.0,1.0,4.0,7.0,3.0,15.0,4.0,5.0,...,0,0,0,0,0,1,0,0,1,0.212598
10941,4.0,9.0,8.0,5.0,16.0,5.0,1.0,1.0,5.0,5.0,...,0,0,0,0,0,1,0,1,0,0.025845
10942,4.0,1.0,3.0,4.0,18.0,5.0,3.0,4.0,9.0,2.0,...,0,0,0,0,0,1,1,0,0,0.091352
10943,5.0,11.0,9.0,5.0,17.0,11.0,2.0,8.0,8.0,1.0,...,1,0,0,0,0,0,1,0,0,-0.034714

#### merge 된거  train test 값 동일한지 확인

In [33]:
np.unique(df1_tr.voted_y)

array([-0.33333333, -0.17538462, -0.11111111, -0.08300395, -0.0817942 ,
       -0.06995885, -0.0669145 , -0.06600249, -0.05454545, -0.05304519,
       -0.04964539, -0.04715447, -0.04252401, -0.04203822, -0.04100946,
       -0.03471445, -0.03004292, -0.0295082 , -0.0195122 , -0.01639344,
       -0.0070922 , -0.00420168, -0.00222222,  0.        ,  0.00869565,
        0.01116071,  0.01178992,  0.01538462,  0.01587302,  0.01734104,
        0.02242152,  0.02584493,  0.02754237,  0.02995392,  0.03431373,
        0.04668838,  0.05194805,  0.05383734,  0.05800464,  0.06004141,
        0.07317073,  0.07920792,  0.07972665,  0.07974138,  0.08141962,
        0.09135201,  0.09574468,  0.09859155,  0.10105263,  0.11004785,
        0.11366906,  0.11450382,  0.11772666,  0.11904762,  0.125     ,
        0.13043478,  0.13354037,  0.13392857,  0.13663366,  0.15072084,
        0.152019  ,  0.15841584,  0.16054159,  0.16190476,  0.1627907 ,
        0.16870416,  0.19222462,  0.2       ,  0.20430108,  0.21212121,
        0.21259843,  0.21487603,  0.21568627,  0.23877069,  0.23929471,
        0.25      ,  0.26666667,  0.28358209,  0.30434783,  0.32374101,
        1.        ])

In [34]:
np.unique(df1_te.voted.unique())

array([-0.33333333, -0.17538462, -0.11111111, -0.08300395, -0.0817942 ,
       -0.06995885, -0.0669145 , -0.06600249, -0.05454545, -0.05304519,
       -0.04964539, -0.04715447, -0.04252401, -0.04203822, -0.04100946,
       -0.03471445, -0.03004292, -0.0295082 , -0.0195122 , -0.01639344,
       -0.0070922 , -0.00420168, -0.00222222,  0.        ,  0.00869565,
        0.01116071,  0.01178992,  0.01538462,  0.01587302,  0.01734104,
        0.02242152,  0.02584493,  0.02754237,  0.02995392,  0.03431373,
        0.04668838,  0.05194805,  0.05383734,  0.05800464,  0.06004141,
        0.07317073,  0.07920792,  0.07972665,  0.07974138,  0.08141962,
        0.09135201,  0.09574468,  0.09859155,  0.10105263,  0.11004785,
        0.11366906,  0.11450382,  0.11772666,  0.11904762,  0.125     ,
        0.13043478,  0.13354037,  0.13392857,  0.13663366,  0.15072084,
        0.152019  ,  0.15841584,  0.16054159,  0.16190476,  0.1627907 ,
        0.16870416,  0.19222462,  0.2       ,  0.20430108,  0.21212121,
        0.21259843,  0.21487603,  0.21568627,  0.23877069,  0.23929471,
        0.25      ,  0.26666667,  0.28358209,  0.30434783,  0.32374101,
        1.        ])

### 다시 train test 나누어서

In [35]:
train_X=df1_tr.drop("voted_x", axis=1)
train_Y=df1_tr.voted_x

In [36]:
test_X=df1_te
test_Y=y_test

In [37]:
train_X

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,race_Arab,race_Asian,race_Black,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married,voted_y
0,5.0,11.0,3.0,5.0,18.0,4.0,1.0,14.0,4.0,1.0,...,0,0,0,0,0,1,0,1,0,-0.041009
1,3.0,19.0,8.0,2.0,8.0,6.0,5.0,7.0,5.0,3.0,...,0,0,0,0,0,1,0,1,0,0.158416
2,5.0,7.0,5.0,4.0,18.0,3.0,5.0,11.0,1.0,4.0,...,0,0,0,0,0,1,0,1,0,0.027542
3,2.0,17.0,7.0,1.0,12.0,4.0,4.0,14.0,4.0,4.0,...,0,1,0,0,0,0,0,1,0,0.079208
4,5.0,13.0,6.0,5.0,20.0,5.0,2.0,4.0,6.0,1.0,...,0,0,0,0,0,1,0,1,0,-0.047154
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43769,4.0,19.0,6.0,5.0,3.0,19.0,3.0,9.0,10.0,3.0,...,0,1,0,0,0,0,0,1,0,0.101053
43770,5.0,3.0,11.0,5.0,11.0,7.0,5.0,16.0,7.0,3.0,...,0,0,1,0,0,0,0,1,0,0.081420
43771,4.0,7.0,11.0,3.0,12.0,6.0,2.0,13.0,82.0,2.0,...,0,0,0,0,0,1,0,1,0,-0.029508
43772,4.0,17.0,5.0,5.0,19.0,3.0,5.0,13.0,13.0,4.0,...,0,0,0,0,0,1,0,1,0,-0.004202
43773,1.0,10.0,11.0,1.0,3.0,5.0,3.0,14.0,5.0,5.0,...,0,0,0,0,0,1,0,0,1,0.214876

In [38]:
test_X.columns = train_X.columns

In [39]:
test_X

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,race_Arab,race_Asian,race_Black,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married,voted_y
0,2.0,17.0,5.0,2.0,20.0,11.0,5.0,1.0,30.0,3.0,...,0,0,0,0,0,1,0,1,0,0.011790
1,1.0,15.0,5.0,2.0,4.0,6.0,2.0,9.0,5.0,5.0,...,0,0,0,0,0,1,0,1,0,0.079727
2,1.0,9.0,45.0,5.0,18.0,13.0,1.0,5.0,30.0,5.0,...,0,0,0,0,0,1,0,1,0,0.114504
3,5.0,19.0,7.0,2.0,6.0,11.0,2.0,1.0,10.0,1.0,...,0,0,0,0,0,1,0,1,0,0.025845
4,5.0,20.0,2.0,4.0,8.0,2.0,2.0,1.0,8.0,2.0,...,0,1,0,0,0,0,0,1,0,-0.019512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10939,5.0,3.0,9.0,4.0,13.0,6.0,3.0,6.0,15.0,4.0,...,0,0,0,0,0,1,0,1,0,-0.002222
10940,1.0,3.0,11.0,1.0,4.0,7.0,3.0,15.0,4.0,5.0,...,0,0,0,0,0,1,0,0,1,0.212598
10941,4.0,9.0,8.0,5.0,16.0,5.0,1.0,1.0,5.0,5.0,...,0,0,0,0,0,1,0,1,0,0.025845
10942,4.0,1.0,3.0,4.0,18.0,5.0,3.0,4.0,9.0,2.0,...,0,0,0,0,0,1,1,0,0,0.091352
10943,5.0,11.0,9.0,5.0,17.0,11.0,2.0,8.0,8.0,1.0,...,1,0,0,0,0,0,1,0,0,-0.034714

# 결과확인

In [40]:
# (yes-no)/all 가중 컬럼 추가 후 vote 예측 결과
models_score_df(models, model_names, train_X, test_X, train_Y, test_Y)

      accuracy       AUC  precision    recall        f1
Ada   0.649214  0.642673   0.639074  0.766534  0.697025
GBC   0.654879  0.647928   0.641755  0.779552  0.703974
XGB   0.647752  0.643345   0.647341  0.726784  0.684766
LGBM  0.657072  0.651666   0.650299  0.754036  0.698336

In [41]:
# importance 0된 원본 예측 결과
models_score_df(models, model_names, X_train, X_test, y_train, y_test)

      accuracy       AUC  precision    recall        f1
Ada   0.650402  0.644314   0.641925  0.759590  0.695818
GBC   0.656159  0.649482   0.643907  0.775907  0.703771
XGB   0.648209  0.644031   0.648809  0.723138  0.683960
LGBM  0.657255  0.651714   0.649821  0.756639  0.699174

# Grid search cv

In [42]:
train_X.shape, test_X.shape, train_Y.shape, test_Y.shape

((43774, 222), (10944, 222), (43774,), (10944, 1))

In [43]:
train_X = train_X.rename(columns={"voted_y":"weight"})
train_X

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,race_Arab,race_Asian,race_Black,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married,weight
0,5.0,11.0,3.0,5.0,18.0,4.0,1.0,14.0,4.0,1.0,...,0,0,0,0,0,1,0,1,0,-0.041009
1,3.0,19.0,8.0,2.0,8.0,6.0,5.0,7.0,5.0,3.0,...,0,0,0,0,0,1,0,1,0,0.158416
2,5.0,7.0,5.0,4.0,18.0,3.0,5.0,11.0,1.0,4.0,...,0,0,0,0,0,1,0,1,0,0.027542
3,2.0,17.0,7.0,1.0,12.0,4.0,4.0,14.0,4.0,4.0,...,0,1,0,0,0,0,0,1,0,0.079208
4,5.0,13.0,6.0,5.0,20.0,5.0,2.0,4.0,6.0,1.0,...,0,0,0,0,0,1,0,1,0,-0.047154
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43769,4.0,19.0,6.0,5.0,3.0,19.0,3.0,9.0,10.0,3.0,...,0,1,0,0,0,0,0,1,0,0.101053
43770,5.0,3.0,11.0,5.0,11.0,7.0,5.0,16.0,7.0,3.0,...,0,0,1,0,0,0,0,1,0,0.081420
43771,4.0,7.0,11.0,3.0,12.0,6.0,2.0,13.0,82.0,2.0,...,0,0,0,0,0,1,0,1,0,-0.029508
43772,4.0,17.0,5.0,5.0,19.0,3.0,5.0,13.0,13.0,4.0,...,0,0,0,0,0,1,0,1,0,-0.004202
43773,1.0,10.0,11.0,1.0,3.0,5.0,3.0,14.0,5.0,5.0,...,0,0,0,0,0,1,0,0,1,0.214876

In [44]:
test_X = test_X.rename(columns={"voted_y":"weight"})
test_X

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,race_Arab,race_Asian,race_Black,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married,weight
0,2.0,17.0,5.0,2.0,20.0,11.0,5.0,1.0,30.0,3.0,...,0,0,0,0,0,1,0,1,0,0.011790
1,1.0,15.0,5.0,2.0,4.0,6.0,2.0,9.0,5.0,5.0,...,0,0,0,0,0,1,0,1,0,0.079727
2,1.0,9.0,45.0,5.0,18.0,13.0,1.0,5.0,30.0,5.0,...,0,0,0,0,0,1,0,1,0,0.114504
3,5.0,19.0,7.0,2.0,6.0,11.0,2.0,1.0,10.0,1.0,...,0,0,0,0,0,1,0,1,0,0.025845
4,5.0,20.0,2.0,4.0,8.0,2.0,2.0,1.0,8.0,2.0,...,0,1,0,0,0,0,0,1,0,-0.019512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10939,5.0,3.0,9.0,4.0,13.0,6.0,3.0,6.0,15.0,4.0,...,0,0,0,0,0,1,0,1,0,-0.002222
10940,1.0,3.0,11.0,1.0,4.0,7.0,3.0,15.0,4.0,5.0,...,0,0,0,0,0,1,0,0,1,0.212598
10941,4.0,9.0,8.0,5.0,16.0,5.0,1.0,1.0,5.0,5.0,...,0,0,0,0,0,1,0,1,0,0.025845
10942,4.0,1.0,3.0,4.0,18.0,5.0,3.0,4.0,9.0,2.0,...,0,0,0,0,0,1,1,0,0,0.091352
10943,5.0,11.0,9.0,5.0,17.0,11.0,2.0,8.0,8.0,1.0,...,1,0,0,0,0,0,1,0,0,-0.034714

In [45]:
np.unique(test_X.weight)

array([-0.33333333, -0.17538462, -0.11111111, -0.08300395, -0.0817942 ,
       -0.06995885, -0.0669145 , -0.06600249, -0.05454545, -0.05304519,
       -0.04964539, -0.04715447, -0.04252401, -0.04203822, -0.04100946,
       -0.03471445, -0.03004292, -0.0295082 , -0.0195122 , -0.01639344,
       -0.0070922 , -0.00420168, -0.00222222,  0.        ,  0.00869565,
        0.01116071,  0.01178992,  0.01538462,  0.01587302,  0.01734104,
        0.02242152,  0.02584493,  0.02754237,  0.02995392,  0.03431373,
        0.04668838,  0.05194805,  0.05383734,  0.05800464,  0.06004141,
        0.07317073,  0.07920792,  0.07972665,  0.07974138,  0.08141962,
        0.09135201,  0.09574468,  0.09859155,  0.10105263,  0.11004785,
        0.11366906,  0.11450382,  0.11772666,  0.11904762,  0.125     ,
        0.13043478,  0.13354037,  0.13392857,  0.13663366,  0.15072084,
        0.152019  ,  0.15841584,  0.16054159,  0.16190476,  0.1627907 ,
        0.16870416,  0.19222462,  0.2       ,  0.20430108,  0.21212121,
        0.21259843,  0.21487603,  0.21568627,  0.23877069,  0.23929471,
        0.25      ,  0.26666667,  0.28358209,  0.30434783,  0.32374101,
        1.        ])

In [46]:
np.unique(train_X.weight)

array([-0.33333333, -0.17538462, -0.11111111, -0.08300395, -0.0817942 ,
       -0.06995885, -0.0669145 , -0.06600249, -0.05454545, -0.05304519,
       -0.04964539, -0.04715447, -0.04252401, -0.04203822, -0.04100946,
       -0.03471445, -0.03004292, -0.0295082 , -0.0195122 , -0.01639344,
       -0.0070922 , -0.00420168, -0.00222222,  0.        ,  0.00869565,
        0.01116071,  0.01178992,  0.01538462,  0.01587302,  0.01734104,
        0.02242152,  0.02584493,  0.02754237,  0.02995392,  0.03431373,
        0.04668838,  0.05194805,  0.05383734,  0.05800464,  0.06004141,
        0.07317073,  0.07920792,  0.07972665,  0.07974138,  0.08141962,
        0.09135201,  0.09574468,  0.09859155,  0.10105263,  0.11004785,
        0.11366906,  0.11450382,  0.11772666,  0.11904762,  0.125     ,
        0.13043478,  0.13354037,  0.13392857,  0.13663366,  0.15072084,
        0.152019  ,  0.15841584,  0.16054159,  0.16190476,  0.1627907 ,
        0.16870416,  0.19222462,  0.2       ,  0.20430108,  0.21212121,
        0.21259843,  0.21487603,  0.21568627,  0.23877069,  0.23929471,
        0.25      ,  0.26666667,  0.28358209,  0.30434783,  0.32374101,
        1.        ])

In [47]:
train_X.shape, test_X.shape, train_Y.shape, test_Y.shape

((43774, 222), (10944, 222), (43774,), (10944, 1))

In [48]:
params = {'n_estimators': [100],
          'min_samples_leaf': [7, 9, 13],
          'max_depth': [4, 5, 6, 7],
          'learning_rate': [0.05, 0.02, 0.01]}

In [49]:
gbc = GradientBoostingClassifier(max_depth=2, random_state=13)
gridsearch = GridSearchCV(estimator=gbc, param_grid=params, cv =5)

In [ ]:
gridsearch.fit(train_X, train_Y)

In [127]:
import pprint

pp = pprint.PrettyPrinter(indent=4)
pp.pprint(gridsearch.cv_results_)

{   'mean_fit_time': array([0.4926096 , 0.57582989, 0.709795  , 0.76598325]),
    'mean_score_time': array([0.03858819, 0.0398859 , 0.04288459, 0.04363518]),
    'mean_test_score': array([0.63932927, 0.65095713, 0.65209941, 0.65200797]),
    'param_max_depth': masked_array(data=[2, 4, 7, 10],
             mask=[False, False, False, False],
       fill_value='?',
            dtype=object),
    'params': [   {'max_depth': 2},
                  {'max_depth': 4},
                  {'max_depth': 7},
                  {'max_depth': 10}],
    'rank_test_score': array([4, 3, 1, 2], dtype=int32),
    'split0_test_score': array([0.64545974, 0.65471159, 0.65573958, 0.65471159]),
    'split1_test_score': array([0.63780697, 0.6525414 , 0.64934323, 0.65345517]),
    'split2_test_score': array([0.63655054, 0.64717304, 0.64968589, 0.64717304]),
    'split3_test_score': array([0.63814963, 0.65185608, 0.65425471, 0.65562536]),
    'split4_test_score': array([0.63867946, 0.64850354, 0.65147361, 0.64907471]),
    'std_fit_time': array([0.01869488, 0.0121467 , 0.03957695, 0.04798479]),
    'std_score_time': array([0.00204141, 0.00222888, 0.00095379, 0.00177134]),
    'std_test_score': array([0.00314437, 0.00274785, 0.00251831, 0.00330061])}

In [128]:
gridsearch.best_estimator_

LGBMClassifier(max_depth=7, random_state=13)

In [129]:
gridsearch.best_score_

0.6520994054508752

In [130]:
gridsearch.best_params_

{'max_depth': 7}

In [132]:
gridsearch.score(test_X, test_Y)

0.6596308479532164

In [134]:
pred = gridsearch.predict(test_X)
pred

In [ ]:
import pandas as pd

score_df = pd.DataFrame(GridSearch.cv_results_)
score_df[["params", 'rank_test_score', "mean_test_score", "std_test_score"]]