# 가중치

In [1]:
from sklearn.preprocessing import (LabelEncoder, LabelBinarizer, RobustScaler)

In [2]:
from sklearn.model_selection import (train_test_split, cross_val_score, StratifiedKFold ,GridSearchCV)

In [3]:
from sklearn.metrics import (accuracy_score, roc_auc_score, classification_report, confusion_matrix)

In [4]:
from sklearn.tree import DecisionTreeClassifier
from graphviz import Source
from sklearn.tree import export_graphviz

In [5]:
from sklearn.ensemble import GradientBoostingClassifier
import time
import warnings

warnings.filterwarnings('ignore')

In [6]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [7]:
from sklearn.preprocessing import (LabelEncoder, LabelBinarizer, RobustScaler)

In [8]:
from sklearn.model_selection import (train_test_split, cross_val_score, StratifiedKFold ,GridSearchCV)

In [9]:
from sklearn.metrics import (accuracy_score, roc_auc_score, classification_report, confusion_matrix)

In [10]:
from sklearn.tree import DecisionTreeClassifier
from graphviz import Source
from sklearn.tree import export_graphviz

In [11]:
from sklearn.ensemble import GradientBoostingClassifier
import time
import warnings

warnings.filterwarnings('ignore')

In [12]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# ada, gbc, xgb, lgbm 모델 함수

In [13]:
# ada, gbc, xgb, lgbm

In [14]:
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [15]:
ada = AdaBoostClassifier(random_state=13)
gbc = GradientBoostingClassifier(random_state=13)
xgb = XGBClassifier(random_state=13)
lgbm = LGBMClassifier(random_state=13)

In [16]:
models = [ada, gbc, xgb, lgbm]
model_names = ['Ada', 'GBC', 'XGB', 'LGBM']

In [17]:
from sklearn.metrics import (accuracy_score, precision_score, recall_score, 
                             f1_score, roc_auc_score, confusion_matrix)

def get_score(y_test, pred):
    acc = accuracy_score(y_test, pred)
    pre = precision_score(y_test, pred)
    rec = recall_score(y_test, pred)
    f1 = f1_score(y_test, pred)
    auc = roc_auc_score(y_test, pred)
   
    return acc, auc, pre, rec, f1

def print_score(y_test, pred, confusion=False, score=False):
    acc, auc, pre, rec, f1 = get_score(y_test, pred)
    con = confusion_matrix(y_test, pred)
    if confusion==True:
        print('confusion matrix')
        print(con)
        print('='*20)
    
    if score==True:
        print('Accuracy: {0:.4f}, AUC: {1:.4f}'.format(acc, auc))
        print('Recall: {0:.4f}, f1_score: {1:.4f}, precision: {2:.4f}'.format(rec, f1, pre))

In [18]:
def fit_model(model, X_train, X_test, y_train, y_test):
#     skfold = StratifiedKFold(n_splits=5)
#     cv_scores = []
#     for score in ['accuracy', 'roc_auc']:    
#         score_cv = cross_val_score(model, X_train, y_train, scoring=score, cv=5)
#         cv_scores.append(round(score_cv.mean(), 4))
    model.fit(X_train, y_train)
    y_pre_tr = model.predict(X_train)
    y_pre_test = model.predict(X_test)
    
    return get_score(y_test, y_pre_test)

def models_score_df(models, model_names, X_train, X_test, y_train, y_test):
    cols_names = ['accuracy', 'AUC', 'precision', 'recall', 'f1']
    datas = []
    for model in models:
        datas.append(fit_model(model, X_train, X_test, y_train, y_test))
     
    return pd.DataFrame(datas, columns=cols_names, index=model_names)

## train test 불러오기

In [19]:
X_test = pd.read_csv('../MACH_data/X_test_data_without_0feature.csv' )
X_test

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,orientation_Other,race_Arab,race_Asian,race_Black,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married
0,2.0,17.0,5.0,2.0,20.0,11.0,5.0,1.0,30.0,3.0,...,0,0,0,0,0,0,1,0,1,0
1,1.0,15.0,5.0,2.0,4.0,6.0,2.0,9.0,5.0,5.0,...,0,0,0,0,0,0,1,0,1,0
2,1.0,9.0,45.0,5.0,18.0,13.0,1.0,5.0,30.0,5.0,...,0,0,0,0,0,0,1,0,1,0
3,5.0,19.0,7.0,2.0,6.0,11.0,2.0,1.0,10.0,1.0,...,0,0,0,0,0,0,1,0,1,0
4,5.0,20.0,2.0,4.0,8.0,2.0,2.0,1.0,8.0,2.0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10939,5.0,3.0,9.0,4.0,13.0,6.0,3.0,6.0,15.0,4.0,...,0,0,0,0,0,0,1,0,1,0
10940,1.0,3.0,11.0,1.0,4.0,7.0,3.0,15.0,4.0,5.0,...,0,0,0,0,0,0,1,0,0,1
10941,4.0,9.0,8.0,5.0,16.0,5.0,1.0,1.0,5.0,5.0,...,0,0,0,0,0,0,1,0,1,0
10942,4.0,1.0,3.0,4.0,18.0,5.0,3.0,4.0,9.0,2.0,...,0,0,0,0,0,0,1,1,0,0
10943,5.0,11.0,9.0,5.0,17.0,11.0,2.0,8.0,8.0,1.0,...,0,1,0,0,0,0,0,1,0,0

In [20]:
X_train = pd.read_csv('../MACH_data/X_train_data_without_0feature.csv' )
X_train

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,orientation_Other,race_Arab,race_Asian,race_Black,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married
0,5.0,11.0,3.0,5.0,18.0,4.0,1.0,14.0,4.0,1.0,...,0,0,0,0,0,0,1,0,1,0
1,3.0,19.0,8.0,2.0,8.0,6.0,5.0,7.0,5.0,3.0,...,0,0,0,0,0,0,1,0,1,0
2,5.0,7.0,5.0,4.0,18.0,3.0,5.0,11.0,1.0,4.0,...,0,0,0,0,0,0,1,0,1,0
3,2.0,17.0,7.0,1.0,12.0,4.0,4.0,14.0,4.0,4.0,...,0,0,1,0,0,0,0,0,1,0
4,5.0,13.0,6.0,5.0,20.0,5.0,2.0,4.0,6.0,1.0,...,0,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43769,4.0,19.0,6.0,5.0,3.0,19.0,3.0,9.0,10.0,3.0,...,0,0,1,0,0,0,0,0,1,0
43770,5.0,3.0,11.0,5.0,11.0,7.0,5.0,16.0,7.0,3.0,...,0,0,0,1,0,0,0,0,1,0
43771,4.0,7.0,11.0,3.0,12.0,6.0,2.0,13.0,82.0,2.0,...,0,0,0,0,0,0,1,0,1,0
43772,4.0,17.0,5.0,5.0,19.0,3.0,5.0,13.0,13.0,4.0,...,0,0,0,0,0,0,1,0,1,0
43773,1.0,10.0,11.0,1.0,3.0,5.0,3.0,14.0,5.0,5.0,...,0,0,0,0,0,0,1,0,0,1

In [21]:
y_test = pd.read_csv('../MACH_data/Y_test_data_without_0feature.csv' )
y_test

       voted
0          0
1          0
2          1
3          1
4          0
...      ...
10939      1
10940      1
10941      0
10942      0
10943      1

[10944 rows x 1 columns]

In [22]:
y_train = pd.read_csv('../MACH_data/Y_train_data_without_0feature.csv' )
y_train

       voted
0          1
1          1
2          0
3          0
4          1
...      ...
43769      1
43770      0
43771      0
43772      0
43773      0

[43774 rows x 1 columns]

In [23]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((43774, 221), (10944, 221), (43774, 1), (10944, 1))

In [24]:
df_tr = pd.concat([X_train, y_train], axis=1)
df_tr

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,race_Arab,race_Asian,race_Black,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married,voted
0,5.0,11.0,3.0,5.0,18.0,4.0,1.0,14.0,4.0,1.0,...,0,0,0,0,0,1,0,1,0,1
1,3.0,19.0,8.0,2.0,8.0,6.0,5.0,7.0,5.0,3.0,...,0,0,0,0,0,1,0,1,0,1
2,5.0,7.0,5.0,4.0,18.0,3.0,5.0,11.0,1.0,4.0,...,0,0,0,0,0,1,0,1,0,0
3,2.0,17.0,7.0,1.0,12.0,4.0,4.0,14.0,4.0,4.0,...,0,1,0,0,0,0,0,1,0,0
4,5.0,13.0,6.0,5.0,20.0,5.0,2.0,4.0,6.0,1.0,...,0,0,0,0,0,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43769,4.0,19.0,6.0,5.0,3.0,19.0,3.0,9.0,10.0,3.0,...,0,1,0,0,0,0,0,1,0,1
43770,5.0,3.0,11.0,5.0,11.0,7.0,5.0,16.0,7.0,3.0,...,0,0,1,0,0,0,0,1,0,0
43771,4.0,7.0,11.0,3.0,12.0,6.0,2.0,13.0,82.0,2.0,...,0,0,0,0,0,1,0,1,0,0
43772,4.0,17.0,5.0,5.0,19.0,3.0,5.0,13.0,13.0,4.0,...,0,0,0,0,0,1,0,1,0,0
43773,1.0,10.0,11.0,1.0,3.0,5.0,3.0,14.0,5.0,5.0,...,0,0,0,0,0,1,0,0,1,0

In [25]:
df_te = X_test
df_te

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,orientation_Other,race_Arab,race_Asian,race_Black,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married
0,2.0,17.0,5.0,2.0,20.0,11.0,5.0,1.0,30.0,3.0,...,0,0,0,0,0,0,1,0,1,0
1,1.0,15.0,5.0,2.0,4.0,6.0,2.0,9.0,5.0,5.0,...,0,0,0,0,0,0,1,0,1,0
2,1.0,9.0,45.0,5.0,18.0,13.0,1.0,5.0,30.0,5.0,...,0,0,0,0,0,0,1,0,1,0
3,5.0,19.0,7.0,2.0,6.0,11.0,2.0,1.0,10.0,1.0,...,0,0,0,0,0,0,1,0,1,0
4,5.0,20.0,2.0,4.0,8.0,2.0,2.0,1.0,8.0,2.0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10939,5.0,3.0,9.0,4.0,13.0,6.0,3.0,6.0,15.0,4.0,...,0,0,0,0,0,0,1,0,1,0
10940,1.0,3.0,11.0,1.0,4.0,7.0,3.0,15.0,4.0,5.0,...,0,0,0,0,0,0,1,0,0,1
10941,4.0,9.0,8.0,5.0,16.0,5.0,1.0,1.0,5.0,5.0,...,0,0,0,0,0,0,1,0,1,0
10942,4.0,1.0,3.0,4.0,18.0,5.0,3.0,4.0,9.0,2.0,...,0,0,0,0,0,0,1,1,0,0
10943,5.0,11.0,9.0,5.0,17.0,11.0,2.0,8.0,8.0,1.0,...,0,1,0,0,0,0,0,1,0,0

### weight 계산

In [26]:
df_tr[["voted", "score"]].groupby("score").count()

       voted
score
20.0       5
21.0       2
22.0       5
23.0       6
24.0      23
...      ...
96.0     379
97.0     173
98.0     141
99.0      82
100.0    253

[81 rows x 1 columns]

In [27]:
weight_all_tr = df_tr[["voted", "score"]].groupby("score").count()

In [28]:
weight_yes_tr = df_tr[["voted", "score"]].groupby("score").sum()

In [29]:
weight_no_tr = weight_all_tr - weight_yes_tr

In [30]:
df_weight_tr = (weight_yes_tr - weight_no_tr)/ weight_all_tr

### train test merge

In [31]:
df1_tr = pd.merge(left=df_tr, right=df_weight_tr, how="left", right_index=True, left_on="score")
df1_tr

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,race_Asian,race_Black,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married,voted_x,voted_y
0,5.0,11.0,3.0,5.0,18.0,4.0,1.0,14.0,4.0,1.0,...,0,0,0,0,1,0,1,0,1,-0.041009
1,3.0,19.0,8.0,2.0,8.0,6.0,5.0,7.0,5.0,3.0,...,0,0,0,0,1,0,1,0,1,0.158416
2,5.0,7.0,5.0,4.0,18.0,3.0,5.0,11.0,1.0,4.0,...,0,0,0,0,1,0,1,0,0,0.027542
3,2.0,17.0,7.0,1.0,12.0,4.0,4.0,14.0,4.0,4.0,...,1,0,0,0,0,0,1,0,0,0.079208
4,5.0,13.0,6.0,5.0,20.0,5.0,2.0,4.0,6.0,1.0,...,0,0,0,0,1,0,1,0,1,-0.047154
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43769,4.0,19.0,6.0,5.0,3.0,19.0,3.0,9.0,10.0,3.0,...,1,0,0,0,0,0,1,0,1,0.101053
43770,5.0,3.0,11.0,5.0,11.0,7.0,5.0,16.0,7.0,3.0,...,0,1,0,0,0,0,1,0,0,0.081420
43771,4.0,7.0,11.0,3.0,12.0,6.0,2.0,13.0,82.0,2.0,...,0,0,0,0,1,0,1,0,0,-0.029508
43772,4.0,17.0,5.0,5.0,19.0,3.0,5.0,13.0,13.0,4.0,...,0,0,0,0,1,0,1,0,0,-0.004202
43773,1.0,10.0,11.0,1.0,3.0,5.0,3.0,14.0,5.0,5.0,...,0,0,0,0,1,0,0,1,0,0.214876

In [32]:
df1_te = pd.merge(left=df_te, right=df_weight_tr, how="left", right_index=True, left_on="score")
df1_te

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,race_Arab,race_Asian,race_Black,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married,voted
0,2.0,17.0,5.0,2.0,20.0,11.0,5.0,1.0,30.0,3.0,...,0,0,0,0,0,1,0,1,0,0.011790
1,1.0,15.0,5.0,2.0,4.0,6.0,2.0,9.0,5.0,5.0,...,0,0,0,0,0,1,0,1,0,0.079727
2,1.0,9.0,45.0,5.0,18.0,13.0,1.0,5.0,30.0,5.0,...,0,0,0,0,0,1,0,1,0,0.114504
3,5.0,19.0,7.0,2.0,6.0,11.0,2.0,1.0,10.0,1.0,...,0,0,0,0,0,1,0,1,0,0.025845
4,5.0,20.0,2.0,4.0,8.0,2.0,2.0,1.0,8.0,2.0,...,0,1,0,0,0,0,0,1,0,-0.019512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10939,5.0,3.0,9.0,4.0,13.0,6.0,3.0,6.0,15.0,4.0,...,0,0,0,0,0,1,0,1,0,-0.002222
10940,1.0,3.0,11.0,1.0,4.0,7.0,3.0,15.0,4.0,5.0,...,0,0,0,0,0,1,0,0,1,0.212598
10941,4.0,9.0,8.0,5.0,16.0,5.0,1.0,1.0,5.0,5.0,...,0,0,0,0,0,1,0,1,0,0.025845
10942,4.0,1.0,3.0,4.0,18.0,5.0,3.0,4.0,9.0,2.0,...,0,0,0,0,0,1,1,0,0,0.091352
10943,5.0,11.0,9.0,5.0,17.0,11.0,2.0,8.0,8.0,1.0,...,1,0,0,0,0,0,1,0,0,-0.034714

#### merge 된거  train test 값 동일한지 확인

In [33]:
np.unique(df1_tr.voted_y)

array([-0.33333333, -0.17538462, -0.11111111, -0.08300395, -0.0817942 ,
       -0.06995885, -0.0669145 , -0.06600249, -0.05454545, -0.05304519,
       -0.04964539, -0.04715447, -0.04252401, -0.04203822, -0.04100946,
       -0.03471445, -0.03004292, -0.0295082 , -0.0195122 , -0.01639344,
       -0.0070922 , -0.00420168, -0.00222222,  0.        ,  0.00869565,
        0.01116071,  0.01178992,  0.01538462,  0.01587302,  0.01734104,
        0.02242152,  0.02584493,  0.02754237,  0.02995392,  0.03431373,
        0.04668838,  0.05194805,  0.05383734,  0.05800464,  0.06004141,
        0.07317073,  0.07920792,  0.07972665,  0.07974138,  0.08141962,
        0.09135201,  0.09574468,  0.09859155,  0.10105263,  0.11004785,
        0.11366906,  0.11450382,  0.11772666,  0.11904762,  0.125     ,
        0.13043478,  0.13354037,  0.13392857,  0.13663366,  0.15072084,
        0.152019  ,  0.15841584,  0.16054159,  0.16190476,  0.1627907 ,
        0.16870416,  0.19222462,  0.2       ,  0.20430108,  0.21212121,
        0.21259843,  0.21487603,  0.21568627,  0.23877069,  0.23929471,
        0.25      ,  0.26666667,  0.28358209,  0.30434783,  0.32374101,
        1.        ])

In [34]:
np.unique(df1_te.voted.unique())

array([-0.33333333, -0.17538462, -0.11111111, -0.08300395, -0.0817942 ,
       -0.06995885, -0.0669145 , -0.06600249, -0.05454545, -0.05304519,
       -0.04964539, -0.04715447, -0.04252401, -0.04203822, -0.04100946,
       -0.03471445, -0.03004292, -0.0295082 , -0.0195122 , -0.01639344,
       -0.0070922 , -0.00420168, -0.00222222,  0.        ,  0.00869565,
        0.01116071,  0.01178992,  0.01538462,  0.01587302,  0.01734104,
        0.02242152,  0.02584493,  0.02754237,  0.02995392,  0.03431373,
        0.04668838,  0.05194805,  0.05383734,  0.05800464,  0.06004141,
        0.07317073,  0.07920792,  0.07972665,  0.07974138,  0.08141962,
        0.09135201,  0.09574468,  0.09859155,  0.10105263,  0.11004785,
        0.11366906,  0.11450382,  0.11772666,  0.11904762,  0.125     ,
        0.13043478,  0.13354037,  0.13392857,  0.13663366,  0.15072084,
        0.152019  ,  0.15841584,  0.16054159,  0.16190476,  0.1627907 ,
        0.16870416,  0.19222462,  0.2       ,  0.20430108,  0.21212121,
        0.21259843,  0.21487603,  0.21568627,  0.23877069,  0.23929471,
        0.25      ,  0.26666667,  0.28358209,  0.30434783,  0.32374101,
        1.        ])

### 다시 train test 나누어서

In [35]:
train_X=df1_tr.drop("voted_x", axis=1)
train_Y=df1_tr.voted_x

In [36]:
test_X=df1_te
test_Y=y_test

In [37]:
train_X

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,race_Arab,race_Asian,race_Black,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married,voted_y
0,5.0,11.0,3.0,5.0,18.0,4.0,1.0,14.0,4.0,1.0,...,0,0,0,0,0,1,0,1,0,-0.041009
1,3.0,19.0,8.0,2.0,8.0,6.0,5.0,7.0,5.0,3.0,...,0,0,0,0,0,1,0,1,0,0.158416
2,5.0,7.0,5.0,4.0,18.0,3.0,5.0,11.0,1.0,4.0,...,0,0,0,0,0,1,0,1,0,0.027542
3,2.0,17.0,7.0,1.0,12.0,4.0,4.0,14.0,4.0,4.0,...,0,1,0,0,0,0,0,1,0,0.079208
4,5.0,13.0,6.0,5.0,20.0,5.0,2.0,4.0,6.0,1.0,...,0,0,0,0,0,1,0,1,0,-0.047154
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43769,4.0,19.0,6.0,5.0,3.0,19.0,3.0,9.0,10.0,3.0,...,0,1,0,0,0,0,0,1,0,0.101053
43770,5.0,3.0,11.0,5.0,11.0,7.0,5.0,16.0,7.0,3.0,...,0,0,1,0,0,0,0,1,0,0.081420
43771,4.0,7.0,11.0,3.0,12.0,6.0,2.0,13.0,82.0,2.0,...,0,0,0,0,0,1,0,1,0,-0.029508
43772,4.0,17.0,5.0,5.0,19.0,3.0,5.0,13.0,13.0,4.0,...,0,0,0,0,0,1,0,1,0,-0.004202
43773,1.0,10.0,11.0,1.0,3.0,5.0,3.0,14.0,5.0,5.0,...,0,0,0,0,0,1,0,0,1,0.214876

In [38]:
test_X.columns = train_X.columns

In [39]:
test_X

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,race_Arab,race_Asian,race_Black,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married,voted_y
0,2.0,17.0,5.0,2.0,20.0,11.0,5.0,1.0,30.0,3.0,...,0,0,0,0,0,1,0,1,0,0.011790
1,1.0,15.0,5.0,2.0,4.0,6.0,2.0,9.0,5.0,5.0,...,0,0,0,0,0,1,0,1,0,0.079727
2,1.0,9.0,45.0,5.0,18.0,13.0,1.0,5.0,30.0,5.0,...,0,0,0,0,0,1,0,1,0,0.114504
3,5.0,19.0,7.0,2.0,6.0,11.0,2.0,1.0,10.0,1.0,...,0,0,0,0,0,1,0,1,0,0.025845
4,5.0,20.0,2.0,4.0,8.0,2.0,2.0,1.0,8.0,2.0,...,0,1,0,0,0,0,0,1,0,-0.019512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10939,5.0,3.0,9.0,4.0,13.0,6.0,3.0,6.0,15.0,4.0,...,0,0,0,0,0,1,0,1,0,-0.002222
10940,1.0,3.0,11.0,1.0,4.0,7.0,3.0,15.0,4.0,5.0,...,0,0,0,0,0,1,0,0,1,0.212598
10941,4.0,9.0,8.0,5.0,16.0,5.0,1.0,1.0,5.0,5.0,...,0,0,0,0,0,1,0,1,0,0.025845
10942,4.0,1.0,3.0,4.0,18.0,5.0,3.0,4.0,9.0,2.0,...,0,0,0,0,0,1,1,0,0,0.091352
10943,5.0,11.0,9.0,5.0,17.0,11.0,2.0,8.0,8.0,1.0,...,1,0,0,0,0,0,1,0,0,-0.034714

# 결과확인

In [40]:
# (yes-no)/all 가중 컬럼 추가 후 vote 예측 결과
models_score_df(models, model_names, train_X, test_X, train_Y, test_Y)

      accuracy       AUC  precision    recall        f1
Ada   0.649214  0.642673   0.639074  0.766534  0.697025
GBC   0.654879  0.647928   0.641755  0.779552  0.703974
XGB   0.647752  0.643345   0.647341  0.726784  0.684766
LGBM  0.657072  0.651666   0.650299  0.754036  0.698336

In [41]:
# importance 0된 원본 예측 결과
models_score_df(models, model_names, X_train, X_test, y_train, y_test)

      accuracy       AUC  precision    recall        f1
Ada   0.650402  0.644314   0.641925  0.759590  0.695818
GBC   0.656159  0.649482   0.643907  0.775907  0.703771
XGB   0.648209  0.644031   0.648809  0.723138  0.683960
LGBM  0.657255  0.651714   0.649821  0.756639  0.699174

# Grid search cv

In [42]:
train_X.shape, test_X.shape, train_Y.shape, test_Y.shape

((43774, 222), (10944, 222), (43774,), (10944, 1))

In [43]:
train_X = train_X.rename(columns={"voted_y":"weight"})
train_X

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,race_Arab,race_Asian,race_Black,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married,weight
0,5.0,11.0,3.0,5.0,18.0,4.0,1.0,14.0,4.0,1.0,...,0,0,0,0,0,1,0,1,0,-0.041009
1,3.0,19.0,8.0,2.0,8.0,6.0,5.0,7.0,5.0,3.0,...,0,0,0,0,0,1,0,1,0,0.158416
2,5.0,7.0,5.0,4.0,18.0,3.0,5.0,11.0,1.0,4.0,...,0,0,0,0,0,1,0,1,0,0.027542
3,2.0,17.0,7.0,1.0,12.0,4.0,4.0,14.0,4.0,4.0,...,0,1,0,0,0,0,0,1,0,0.079208
4,5.0,13.0,6.0,5.0,20.0,5.0,2.0,4.0,6.0,1.0,...,0,0,0,0,0,1,0,1,0,-0.047154
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43769,4.0,19.0,6.0,5.0,3.0,19.0,3.0,9.0,10.0,3.0,...,0,1,0,0,0,0,0,1,0,0.101053
43770,5.0,3.0,11.0,5.0,11.0,7.0,5.0,16.0,7.0,3.0,...,0,0,1,0,0,0,0,1,0,0.081420
43771,4.0,7.0,11.0,3.0,12.0,6.0,2.0,13.0,82.0,2.0,...,0,0,0,0,0,1,0,1,0,-0.029508
43772,4.0,17.0,5.0,5.0,19.0,3.0,5.0,13.0,13.0,4.0,...,0,0,0,0,0,1,0,1,0,-0.004202
43773,1.0,10.0,11.0,1.0,3.0,5.0,3.0,14.0,5.0,5.0,...,0,0,0,0,0,1,0,0,1,0.214876

In [44]:
test_X = test_X.rename(columns={"voted_y":"weight"})
test_X

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,race_Arab,race_Asian,race_Black,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married,weight
0,2.0,17.0,5.0,2.0,20.0,11.0,5.0,1.0,30.0,3.0,...,0,0,0,0,0,1,0,1,0,0.011790
1,1.0,15.0,5.0,2.0,4.0,6.0,2.0,9.0,5.0,5.0,...,0,0,0,0,0,1,0,1,0,0.079727
2,1.0,9.0,45.0,5.0,18.0,13.0,1.0,5.0,30.0,5.0,...,0,0,0,0,0,1,0,1,0,0.114504
3,5.0,19.0,7.0,2.0,6.0,11.0,2.0,1.0,10.0,1.0,...,0,0,0,0,0,1,0,1,0,0.025845
4,5.0,20.0,2.0,4.0,8.0,2.0,2.0,1.0,8.0,2.0,...,0,1,0,0,0,0,0,1,0,-0.019512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10939,5.0,3.0,9.0,4.0,13.0,6.0,3.0,6.0,15.0,4.0,...,0,0,0,0,0,1,0,1,0,-0.002222
10940,1.0,3.0,11.0,1.0,4.0,7.0,3.0,15.0,4.0,5.0,...,0,0,0,0,0,1,0,0,1,0.212598
10941,4.0,9.0,8.0,5.0,16.0,5.0,1.0,1.0,5.0,5.0,...,0,0,0,0,0,1,0,1,0,0.025845
10942,4.0,1.0,3.0,4.0,18.0,5.0,3.0,4.0,9.0,2.0,...,0,0,0,0,0,1,1,0,0,0.091352
10943,5.0,11.0,9.0,5.0,17.0,11.0,2.0,8.0,8.0,1.0,...,1,0,0,0,0,0,1,0,0,-0.034714

In [45]:
np.unique(test_X.weight)

array([-0.33333333, -0.17538462, -0.11111111, -0.08300395, -0.0817942 ,
       -0.06995885, -0.0669145 , -0.06600249, -0.05454545, -0.05304519,
       -0.04964539, -0.04715447, -0.04252401, -0.04203822, -0.04100946,
       -0.03471445, -0.03004292, -0.0295082 , -0.0195122 , -0.01639344,
       -0.0070922 , -0.00420168, -0.00222222,  0.        ,  0.00869565,
        0.01116071,  0.01178992,  0.01538462,  0.01587302,  0.01734104,
        0.02242152,  0.02584493,  0.02754237,  0.02995392,  0.03431373,
        0.04668838,  0.05194805,  0.05383734,  0.05800464,  0.06004141,
        0.07317073,  0.07920792,  0.07972665,  0.07974138,  0.08141962,
        0.09135201,  0.09574468,  0.09859155,  0.10105263,  0.11004785,
        0.11366906,  0.11450382,  0.11772666,  0.11904762,  0.125     ,
        0.13043478,  0.13354037,  0.13392857,  0.13663366,  0.15072084,
        0.152019  ,  0.15841584,  0.16054159,  0.16190476,  0.1627907 ,
        0.16870416,  0.19222462,  0.2       ,  0.20430108,  0.21212121,
        0.21259843,  0.21487603,  0.21568627,  0.23877069,  0.23929471,
        0.25      ,  0.26666667,  0.28358209,  0.30434783,  0.32374101,
        1.        ])

In [46]:
np.unique(train_X.weight)

array([-0.33333333, -0.17538462, -0.11111111, -0.08300395, -0.0817942 ,
       -0.06995885, -0.0669145 , -0.06600249, -0.05454545, -0.05304519,
       -0.04964539, -0.04715447, -0.04252401, -0.04203822, -0.04100946,
       -0.03471445, -0.03004292, -0.0295082 , -0.0195122 , -0.01639344,
       -0.0070922 , -0.00420168, -0.00222222,  0.        ,  0.00869565,
        0.01116071,  0.01178992,  0.01538462,  0.01587302,  0.01734104,
        0.02242152,  0.02584493,  0.02754237,  0.02995392,  0.03431373,
        0.04668838,  0.05194805,  0.05383734,  0.05800464,  0.06004141,
        0.07317073,  0.07920792,  0.07972665,  0.07974138,  0.08141962,
        0.09135201,  0.09574468,  0.09859155,  0.10105263,  0.11004785,
        0.11366906,  0.11450382,  0.11772666,  0.11904762,  0.125     ,
        0.13043478,  0.13354037,  0.13392857,  0.13663366,  0.15072084,
        0.152019  ,  0.15841584,  0.16054159,  0.16190476,  0.1627907 ,
        0.16870416,  0.19222462,  0.2       ,  0.20430108,  0.21212121,
        0.21259843,  0.21487603,  0.21568627,  0.23877069,  0.23929471,
        0.25      ,  0.26666667,  0.28358209,  0.30434783,  0.32374101,
        1.        ])

In [47]:
train_X.shape, test_X.shape, train_Y.shape, test_Y.shape

((43774, 222), (10944, 222), (43774,), (10944, 1))

In [48]:
params = {'n_estimators': [100],
          'min_samples_leaf': [7, 9, 13],
          'max_depth': [4, 5, 6, 7],
          'learning_rate': [0.05, 0.02, 0.01]}

In [49]:
gbc = GradientBoostingClassifier(max_depth=2, random_state=13)
gridsearch = GridSearchCV(estimator=gbc, param_grid=params, cv =5)

In [51]:
gridsearch.fit(train_X, train_Y)

KeyboardInterrupt:

In [52]:
import pprint

pp = pprint.PrettyPrinter(indent=4)
pp.pprint(gridsearch.cv_results_)

{   'mean_fit_time': array([33.23486385, 34.21392155, 32.11872592, 42.47677755, 43.04066963,
       44.36280103, 53.55688224, 56.00577221, 55.19000511, 65.6263968 ,
       66.46401124, 66.68042231, 37.31081762, 36.9075325 , 35.20986457,
       44.55692849, 43.81268907, 44.14442172, 57.55548863, 54.46150007,
       55.73950958, 66.29857569, 66.73664494, 69.29765282, 36.56430783,
       37.31035261, 37.85985403, 49.58827324, 47.86163239, 48.45262256,
       59.9036552 , 60.55737557, 59.62732768, 70.57170725, 69.16749811,
       72.09823675]),
    'mean_score_time': array([0.04315901, 0.04227076, 0.03855448, 0.04430447, 0.04766498,
       0.04876933, 0.04969964, 0.05376034, 0.05209455, 0.05928421,
       0.06408715, 0.05714502, 0.04567366, 0.04584141, 0.04446249,
       0.04948616, 0.04755416, 0.04868326, 0.05576682, 0.0537683 ,
       0.05751801, 0.05989752, 0.06279297, 0.06498604, 0.04408441,
       0.05004096, 0.04543729, 0.04903178, 0.05099673, 0.0561408 ,
       0.0610702 , 0.06464019, 0.06445818, 0.06230884, 0.06145883,
       0.0697319 ]),
    'mean_test_score': array([0.64718776, 0.64684504, 0.6464339 , 0.64928943, 0.64949509,
       0.64903819, 0.65002048, 0.65123129, 0.65191657, 0.65050026,
       0.65152831, 0.65091147, 0.63398363, 0.63425775, 0.63343536,
       0.63894093, 0.63896374, 0.63887235, 0.64325847, 0.64268738,
       0.64209341, 0.64419513, 0.64371543, 0.64449209, 0.62454877,
       0.6246173 , 0.62450306, 0.6314707 , 0.63151639, 0.63135648,
       0.63549134, 0.63581116, 0.63510295, 0.63731895, 0.6373875 ,
       0.63773016]),
    'param_learning_rate': masked_array(data=[0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05,
                   0.05, 0.05, 0.05, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02,
                   0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.01, 0.01, 0.01,
                   0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value='?',
            dtype=object),
    'param_max_depth': masked_array(data=[4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 4, 4, 4, 5, 5, 5,
                   6, 6, 6, 7, 7, 7, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value='?',
            dtype=object),
    'param_min_samples_leaf': masked_array(data=[7, 9, 13, 7, 9, 13, 7, 9, 13, 7, 9, 13, 7, 9, 13, 7, 9,
                   13, 7, 9, 13, 7, 9, 13, 7, 9, 13, 7, 9, 13, 7, 9, 13,
                   7, 9, 13],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value='?',
            dtype=object),
    'param_n_estimators': masked_array(data=[100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
                   100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
                   100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
                   100, 100, 100],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value='?',
            dtype=object),
    'params': [   {   'learning_rate': 0.05,
                      'max_depth': 4,
                      'min_samples_leaf': 7,
                      'n_estimators': 100},
                  {   'learning_rate': 0.05,
                      'max_depth': 4,
                      'min_samples_leaf': 9,
                      'n_estimators': 100},
                  {   'learning_rate': 0.05,
                      'max_depth': 4,
                      'min_samples_leaf': 13,
                      'n_estimators': 100},
                  {   'learning_rate': 0.05,
                      'max_depth': 5,
                      'min_samples_leaf': 7,
                      'n_estimators': 100},
                  {   'learning_rate': 0.05,
                      'max_depth': 5,
                      'min_samples_leaf': 9,
                      'n_estimators': 100},
                  {   'learning_rate': 0.05,
                      'max_depth': 5,
                      'min_samples_leaf': 13,
                      'n_estimators': 100},
                  {   'learning_rate': 0.05,
                      'max_depth': 6,
                      'min_samples_leaf': 7,
                      'n_estimators': 100},
                  {   'learning_rate': 0.05,
                      'max_depth': 6,
                      'min_samples_leaf': 9,
                      'n_estimators': 100},
                  {   'learning_rate': 0.05,
                      'max_depth': 6,
                      'min_samples_leaf': 13,
                      'n_estimators': 100},
                  {   'learning_rate': 0.05,
                      'max_depth': 7,
                      'min_samples_leaf': 7,
                      'n_estimators': 100},
                  {   'learning_rate': 0.05,
                      'max_depth': 7,
                      'min_samples_leaf': 9,
                      'n_estimators': 100},
                  {   'learning_rate': 0.05,
                      'max_depth': 7,
                      'min_samples_leaf': 13,
                      'n_estimators': 100},
                  {   'learning_rate': 0.02,
                      'max_depth': 4,
                      'min_samples_leaf': 7,
                      'n_estimators': 100},
                  {   'learning_rate': 0.02,
                      'max_depth': 4,
                      'min_samples_leaf': 9,
                      'n_estimators': 100},
                  {   'learning_rate': 0.02,
                      'max_depth': 4,
                      'min_samples_leaf': 13,
                      'n_estimators': 100},
                  {   'learning_rate': 0.02,
                      'max_depth': 5,
                      'min_samples_leaf': 7,
                      'n_estimators': 100},
                  {   'learning_rate': 0.02,
                      'max_depth': 5,
                      'min_samples_leaf': 9,
                      'n_estimators': 100},
                  {   'learning_rate': 0.02,
                      'max_depth': 5,
                      'min_samples_leaf': 13,
                      'n_estimators': 100},
                  {   'learning_rate': 0.02,
                      'max_depth': 6,
                      'min_samples_leaf': 7,
                      'n_estimators': 100},
                  {   'learning_rate': 0.02,
                      'max_depth': 6,
                      'min_samples_leaf': 9,
                      'n_estimators': 100},
                  {   'learning_rate': 0.02,
                      'max_depth': 6,
                      'min_samples_leaf': 13,
                      'n_estimators': 100},
                  {   'learning_rate': 0.02,
                      'max_depth': 7,
                      'min_samples_leaf': 7,
                      'n_estimators': 100},
                  {   'learning_rate': 0.02,
                      'max_depth': 7,
                      'min_samples_leaf': 9,
                      'n_estimators': 100},
                  {   'learning_rate': 0.02,
                      'max_depth': 7,
                      'min_samples_leaf': 13,
                      'n_estimators': 100},
                  {   'learning_rate': 0.01,
                      'max_depth': 4,
                      'min_samples_leaf': 7,
                      'n_estimators': 100},
                  {   'learning_rate': 0.01,
                      'max_depth': 4,
                      'min_samples_leaf': 9,
                      'n_estimators': 100},
                  {   'learning_rate': 0.01,
                      'max_depth': 4,
                      'min_samples_leaf': 13,
                      'n_estimators': 100},
                  {   'learning_rate': 0.01,
                      'max_depth': 5,
                      'min_samples_leaf': 7,
                      'n_estimators': 100},
                  {   'learning_rate': 0.01,
                      'max_depth': 5,
                      'min_samples_leaf': 9,
                      'n_estimators': 100},
                  {   'learning_rate': 0.01,
                      'max_depth': 5,
                      'min_samples_leaf': 13,
                      'n_estimators': 100},
                  {   'learning_rate': 0.01,
                      'max_depth': 6,
                      'min_samples_leaf': 7,
                      'n_estimators': 100},
                  {   'learning_rate': 0.01,
                      'max_depth': 6,
                      'min_samples_leaf': 9,
                      'n_estimators': 100},
                  {   'learning_rate': 0.01,
                      'max_depth': 6,
                      'min_samples_leaf': 13,
                      'n_estimators': 100},
                  {   'learning_rate': 0.01,
                      'max_depth': 7,
                      'min_samples_leaf': 7,
                      'n_estimators': 100},
                  {   'learning_rate': 0.01,
                      'max_depth': 7,
                      'min_samples_leaf': 9,
                      'n_estimators': 100},
                  {   'learning_rate': 0.01,
                      'max_depth': 7,
                      'min_samples_leaf': 13,
                      'n_estimators': 100}],
    'rank_test_score': array([10, 11, 12,  8,  7,  9,  6,  3,  1,  5,  2,  4, 29, 28, 30, 20, 19,
       21, 16, 17, 18, 14, 15, 13, 35, 34, 36, 32, 31, 33, 26, 25, 27, 24,
       23, 22], dtype=int32),
    'split0_test_score': array([0.65562536, 0.65436893, 0.65471159, 0.65516848, 0.65608224,
       0.65619646, 0.65539692, 0.6552827 , 0.65608224, 0.65471159,
       0.65505425, 0.65516848, 0.63917761, 0.63997716, 0.63780697,
       0.64397487, 0.64488864, 0.64306111, 0.65471159, 0.65288407,
       0.65208452, 0.65219874, 0.6513992 , 0.65208452, 0.62741291,
       0.62741291, 0.62844089, 0.63986294, 0.63929183, 0.63929183,
       0.63986294, 0.6407767 , 0.63872073, 0.64294689, 0.64089092,
       0.6413478 ]),
    'split1_test_score': array([0.64660194, 0.64717304, 0.64466019, 0.6513992 , 0.64762993,
       0.64900057, 0.64900057, 0.65208452, 0.65219874, 0.64865791,
       0.64900057, 0.65037122, 0.63175328, 0.6318675 , 0.63003998,
       0.63723587, 0.63757853, 0.63814963, 0.63929183, 0.63963449,
       0.63929183, 0.63974872, 0.63997716, 0.64111936, 0.62364363,
       0.62364363, 0.62352941, 0.62981154, 0.63095374, 0.63026842,
       0.6351799 , 0.63483724, 0.63495146, 0.63529412, 0.63426613,
       0.63540834]),
    'split2_test_score': array([0.64260423, 0.64340377, 0.64477441, 0.64568818, 0.64717304,
       0.64443175, 0.64797259, 0.64785837, 0.65014278, 0.64877213,
       0.64785837, 0.64762993, 0.63369503, 0.63460879, 0.63449457,
       0.63495146, 0.63506568, 0.635751  , 0.64031982, 0.63860651,
       0.63757853, 0.64283267, 0.63952027, 0.64260423, 0.62592804,
       0.62592804, 0.62547116, 0.62809823, 0.62809823, 0.62786979,
       0.63358081, 0.63380925, 0.63300971, 0.63312393, 0.63460879,
       0.6351799 ]),
    'split3_test_score': array([0.64671616, 0.64751571, 0.64420331, 0.64945745, 0.64911479,
       0.64888635, 0.65105654, 0.65117076, 0.65322673, 0.65162764,
       0.65391205, 0.6519703 , 0.63209595, 0.63163906, 0.63175328,
       0.63929183, 0.63963449, 0.64009138, 0.64237579, 0.64237579,
       0.64260423, 0.64454597, 0.64466019, 0.6452313 , 0.62352941,
       0.62375785, 0.62375785, 0.6295831 , 0.62935465, 0.62924043,
       0.63529412, 0.63597944, 0.63712164, 0.63814963, 0.63940605,
       0.63917761]),
    'split4_test_score': array([0.64439114, 0.64176377, 0.64381997, 0.64473384, 0.64747544,
       0.64667581, 0.64667581, 0.64976011, 0.64793237, 0.64873201,
       0.65181631, 0.64941741, 0.63319625, 0.63319625, 0.63308202,
       0.63925063, 0.63765136, 0.63730866, 0.63959333, 0.63993603,
       0.63890793, 0.64164953, 0.64302033, 0.64142106, 0.62222984,
       0.62234407, 0.62131597, 0.62999772, 0.62988348, 0.63011195,
       0.63353895, 0.63365319, 0.63171122, 0.63708019, 0.63776559,
       0.63753713]),
    'std_fit_time': array([1.49422985, 1.31454336, 0.11870303, 0.98556446, 1.2728537 ,
       0.57997501, 1.88687479, 0.57860222, 1.02396606, 0.93083202,
       1.09668046, 0.32191227, 0.2991137 , 0.46552043, 1.25061363,
       0.34701199, 0.08371933, 0.42410923, 2.00644638, 0.17788053,
       0.48885958, 0.57438736, 0.65363513, 2.32543495, 1.47037906,
       0.98962538, 1.70216874, 1.55984279, 1.73046046, 1.40382209,
       0.66691344, 0.41609084, 0.71197744, 2.0576567 , 1.80639396,
       0.58013519]),
    'std_score_time': array([0.00425823, 0.00685664, 0.0006784 , 0.00116442, 0.0066739 ,
       0.0042863 , 0.00209463, 0.00169152, 0.00145343, 0.0041105 ,
       0.00246433, 0.00183001, 0.00407793, 0.00292274, 0.00176916,
       0.00261464, 0.00066893, 0.00092574, 0.00236656, 0.00104011,
       0.00339244, 0.00039972, 0.00632862, 0.00773246, 0.0024398 ,
       0.00565871, 0.00216396, 0.00118035, 0.00421399, 0.01323149,
       0.00366241, 0.01050482, 0.0062127 , 0.00301676, 0.00104713,
       0.00589572]),
    'std_test_score': array([0.00448528, 0.00435495, 0.00415279, 0.00381484, 0.0033611 ,
       0.00395134, 0.00304632, 0.00247736, 0.00276294, 0.00238804,
       0.00275882, 0.00255092, 0.00269141, 0.00305065, 0.00263499,
       0.00297935, 0.00329819, 0.0025196 , 0.00582677, 0.0052462 ,
       0.00526239, 0.00429623, 0.00428929, 0.00406355, 0.00186234,
       0.0018104 , 0.00237085, 0.00424944, 0.00399493, 0.00405801,
       0.00231122, 0.00261908, 0.00257184, 0.00328995, 0.00260598,
       0.00232871])}

In [53]:
gridsearch.best_estimator_

GradientBoostingClassifier(learning_rate=0.05, max_depth=6, min_samples_leaf=13,
                           random_state=13)

In [54]:
gridsearch.best_score_

0.6519165718417768

In [55]:
gridsearch.best_params_

{'learning_rate': 0.05,
 'max_depth': 6,
 'min_samples_leaf': 13,
 'n_estimators': 100}

In [56]:
gridsearch.score(test_X, test_Y)

0.653874269005848

In [57]:
pred = gridsearch.predict(test_X)
pred

array([1, 0, 0, ..., 1, 1, 0])

In [58]:
print_score(y_test, pred, confusion=True, score=True)

confusion matrix
[[2707 2476]
 [1312 4449]]
====================
Accuracy: 0.6539, AUC: 0.6473
Recall: 0.7723, f1_score: 0.7014, precision: 0.6425

In [ ]:
import pandas as pd

score_df = pd.DataFrame(GridSearch.cv_results_)
score_df[["params", 'rank_test_score', "mean_test_score", "std_test_score"]]