In [1]:
df = pd.read_csv('../MACH_data/cut_off_by_avg.csv')
df

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,religion,orientation,race,voted,married,familysize,score,v_score,t_score,m_score
0,5.0,17.0,4.0,5.0,9.0,8.0,1.0,16.0,6.0,3.0,...,Agnostic,Heterosexual,White,No,Never married,2,91.0,37.0,45.0,9.0
1,5.0,16.0,4.0,5.0,12.0,3.0,1.0,2.0,7.0,1.0,...,Atheist,Bisexual,Asian,No,Never married,2,98.0,43.0,45.0,10.0
2,2.0,12.0,9.0,4.0,1.0,10.0,2.0,7.0,10.0,1.0,...,Christian(Protestant),Heterosexual,White,Yes,Previously married,2,78.0,37.0,36.0,5.0
3,5.0,13.0,9.0,5.0,7.0,5.0,2.0,19.0,9.0,1.0,...,Christian(Catholic),Homosexual,White,Yes,Never married,2,85.0,35.0,41.0,9.0
4,4.0,4.0,9.0,3.0,5.0,6.0,5.0,15.0,18.0,3.0,...,Agnostic,Heterosexual,Other,No,Never married,3,76.0,36.0,32.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53015,4.0,15.0,5.0,1.0,16.0,5.0,1.0,10.0,5.0,1.0,...,Agnostic,Homosexual,White,Yes,Never married,3,83.0,42.0,34.0,7.0
53016,5.0,1.0,10.0,5.0,13.0,5.0,4.0,15.0,11.0,4.0,...,Other,Heterosexual,Asian,No,Never married,1,64.0,31.0,26.0,7.0
53017,2.0,17.0,10.0,1.0,6.0,14.0,2.0,16.0,25.0,4.0,...,Other,Heterosexual,Asian,No,Currently married,1,59.0,28.0,26.0,5.0
53018,5.0,9.0,6.0,5.0,4.0,4.0,1.0,15.0,7.0,1.0,...,Atheist,Homosexual,White,No,Never married,2,90.0,37.0,43.0,10.0
53019,2.0,17.0,5.0,1.0,18.0,7.0,1.0,9.0,5.0,1.0,...,Agnostic,Heterosexual,White,No,Never married,3,69.0,34.0,27.0,8.0

In [6]:
cols = []
for col in df.columns:
    if ("TYP" in col) | ("VCL" in col) | ("screen" in col) | ("lapse" in col):
        cols.append(col)
cols

['introelapse',
 'testelapse',
 'surveyelapse',
 'TYP_out',
 'TYP_fight',
 'TYP_depnd',
 'TYP_anx',
 'TYP_try',
 'TYP_quiet',
 'TYP_warm',
 'TYP_disorg',
 'TYP_calm',
 'TYP_stable',
 'VCL1',
 'VCL2',
 'VCL3',
 'VCL4',
 'VCL5',
 'VCL6_F',
 'VCL7',
 'VCL8',
 'VCL9_F',
 'VCL10',
 'VCL11',
 'VCL12_F',
 'VCL13',
 'VCL14',
 'VCL15',
 'VCL16',
 'screenw',
 'screenh']

In [10]:
df_tve = df[cols]
df_tve

,introelapse,testelapse,surveyelapse,TYP_out,TYP_fight,TYP_depnd,TYP_anx,TYP_try,TYP_quiet,TYP_warm,...,VCL9_F,VCL10,VCL11,VCL12_F,VCL13,VCL14,VCL15,VCL16,screenw,screenh
0,38.0,143.0,150,2,5,6,2,4,6,5,...,n_know,know,n_know,n_know,know,know,know,know,1536.0,864.0
1,4.0,143.0,157,1,7,6,7,5,7,1,...,know,know,know,know,know,know,know,know,375.0,667.0
2,60.0,191.0,269,6,5,5,7,7,2,6,...,n_know,know,n_know,know,n_know,know,know,know,1280.0,720.0
3,37.0,302.0,334,2,5,5,6,7,6,5,...,n_know,know,n_know,n_know,n_know,n_know,know,know,360.0,640.0
4,3.0,244.0,158,2,4,6,2,3,7,5,...,know,know,n_know,n_know,n_know,know,know,know,1366.0,768.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53015,9.0,151.0,157,7,7,7,5,7,6,2,...,n_know,know,n_know,n_know,n_know,know,n_know,know,375.0,812.0
53016,5.0,237.0,220,7,7,3,4,6,6,4,...,n_know,know,n_know,n_know,n_know,n_know,n_know,know,375.0,667.0
53017,6.0,494.0,340,6,4,5,2,6,6,6,...,n_know,know,n_know,n_know,n_know,n_know,know,know,2048.0,1080.0
53018,6.0,295.0,140,5,7,5,5,5,6,3,...,n_know,know,n_know,n_know,n_know,n_know,know,know,1440.0,900.0
53019,11.0,111.0,122,1,6,1,5,5,6,3,...,n_know,know,n_know,n_know,know,know,know,know,1280.0,1024.0

In [ ]:
from py