## 모델 적용전 범주화 전처리

In [1]:
df = pd.read_csv('../MACH_data/data_cutoff_age18.csv')

In [2]:
from sklearn.preprocessing import RobustScaler

def tran_robust(df):
    num_cols = []
    for col in df.columns:
        if ("E" in col) | ("age" in col) |("family" in col) |("elapse" in col):
            num_cols.append(col)
    rs = RobustScaler()
    df[num_cols] = rs.fit_transform(df[num_cols])
    return df

In [3]:
df = tran_robust(df)

In [4]:
y = df["voted"]
x = df.drop("voted", axis=1)

In [5]:
x.shape, y.shape

((54718, 107), (54718,))

### x get_dummies

In [6]:
X = pd.get_dummies(x)

### y 값 라벨 인코더

In [7]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
Y = lb.fit_transform(y)
Y   # no = 0, yes = 1

array([[1],
       [0],
       [1],
       ...,
       [0],
       [1],
       [0]])

In [8]:
X.shape, Y.shape

((54718, 339), (54718, 1))

In [9]:
X.isnull().sum().sum()

0

In [10]:

aa = pd.DataFrame(X.describe())
bb = aa.loc[:,((aa.loc["max",:] == 1) & (aa.loc["min",:] == 0))]
df1 = X[bb.columns].copy()

datas = []
for i in df1.columns:
    datas.append(i)
data = []
for i in datas:
    if "VCL" not in i:
        data.append(i)

not_vcl = list(set(pd.Series(data).str.split("_").str[0]))
df2 = df1[data]

for index in range(len(not_vcl)):
    
    cc = []
    
    for i,j in enumerate(list(df2.columns)):
        if not_vcl[index] in j:
            cc.append(i)
            
    
    df3 = df2.iloc[:,cc]
    df4 = pd.concat([df3,y], axis=1)
    df5 = pd.DataFrame(df4.groupby("voted").sum())
    df6 = (df5.iloc[1,:] - df5.iloc[0,:])/df5.sum() + 1
    X[df2.iloc[:,cc].columns] = (X[df2.iloc[:,cc].columns]* df6)

In [18]:
X[data]

,country_AE,country_AF,country_AG,country_AL,country_AM,country_AO,country_AR,country_AT,country_AU,country_AZ,...,race_Arab,race_Asian,race_Black,race_Indigenous Australian,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.939524,0.0,0.0,0.000000,0.000000,1.305865,0.000000,0.000000
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.000000,1.152353,0.000000,0.949366,0.000000
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.000000,1.152353,0.000000,0.000000,1.146297
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.000000,1.152353,0.000000,0.949366,0.000000
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.000000,1.152353,0.000000,0.949366,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54713,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.729427,0.000000,0.0,0.0,0.000000,0.000000,1.305865,0.000000,0.000000
54714,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.000000,1.152353,0.000000,0.949366,0.000000
54715,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.000000,1.152353,0.000000,0.949366,0.000000
54716,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.729427,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.949366,0.000000
54717,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.939464,0.000000,0.000000,0.949366,0.000000

In [19]:
X

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,race_Arab,race_Asian,race_Black,race_Indigenous Australian,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married
0,3.0,6.0,2.333333,3.0,7.0,2.6,5.0,20.0,1.166667,2.0,...,0.0,0.000000,0.939524,0.0,0.0,0.000000,0.000000,1.305865,0.000000,0.000000
1,5.0,17.0,-0.500000,5.0,9.0,0.4,1.0,16.0,-0.333333,3.0,...,0.0,0.000000,0.000000,0.0,0.0,0.000000,1.152353,0.000000,0.949366,0.000000
2,2.0,12.0,0.333333,4.0,1.0,0.8,2.0,7.0,0.333333,1.0,...,0.0,0.000000,0.000000,0.0,0.0,0.000000,1.152353,0.000000,0.000000,1.146297
3,5.0,13.0,0.333333,5.0,7.0,-0.2,2.0,19.0,0.166667,1.0,...,0.0,0.000000,0.000000,0.0,0.0,0.000000,1.152353,0.000000,0.949366,0.000000
4,3.0,11.0,-0.500000,3.0,10.0,-0.4,2.0,17.0,-0.500000,4.0,...,0.0,0.000000,0.000000,0.0,0.0,0.000000,1.152353,0.000000,0.949366,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54713,2.0,17.0,0.500000,1.0,6.0,1.6,2.0,16.0,2.833333,4.0,...,0.0,0.729427,0.000000,0.0,0.0,0.000000,0.000000,1.305865,0.000000,0.000000
54714,5.0,9.0,-0.166667,5.0,4.0,-0.4,1.0,15.0,-0.166667,1.0,...,0.0,0.000000,0.000000,0.0,0.0,0.000000,1.152353,0.000000,0.949366,0.000000
54715,2.0,17.0,-0.333333,1.0,18.0,0.2,1.0,9.0,-0.500000,1.0,...,0.0,0.000000,0.000000,0.0,0.0,0.000000,1.152353,0.000000,0.949366,0.000000
54716,4.0,15.0,0.166667,3.0,9.0,0.4,5.0,17.0,0.166667,3.0,...,0.0,0.729427,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.949366,0.000000
54717,3.0,12.0,0.166667,1.0,10.0,0.0,5.0,13.0,4.833333,1.0,...,0.0,0.000000,0.000000,0.0,0.0,0.939464,0.000000,0.000000,0.949366,0.000000

In [20]:
X

,Q1_TP_notell_2u,Q1I,Q1E_notell_2u,Q2_TP_ppl_nd_dangun,Q2I,Q2E_ppl_nd_dangun,Q3_TN_do_moral,Q3I,Q3E_do_moral,Q4_VN_ppl_good,...,race_Arab,race_Asian,race_Black,race_Indigenous Australian,race_Native American,race_Other,race_White,married_Currently married,married_Never married,married_Previously married
0,3.0,6.0,2.333333,3.0,7.0,2.6,5.0,20.0,1.166667,2.0,...,0.0,0.000000,0.939524,0.0,0.0,0.000000,0.000000,1.305865,0.000000,0.000000
1,5.0,17.0,-0.500000,5.0,9.0,0.4,1.0,16.0,-0.333333,3.0,...,0.0,0.000000,0.000000,0.0,0.0,0.000000,1.152353,0.000000,0.949366,0.000000
2,2.0,12.0,0.333333,4.0,1.0,0.8,2.0,7.0,0.333333,1.0,...,0.0,0.000000,0.000000,0.0,0.0,0.000000,1.152353,0.000000,0.000000,1.146297
3,5.0,13.0,0.333333,5.0,7.0,-0.2,2.0,19.0,0.166667,1.0,...,0.0,0.000000,0.000000,0.0,0.0,0.000000,1.152353,0.000000,0.949366,0.000000
4,3.0,11.0,-0.500000,3.0,10.0,-0.4,2.0,17.0,-0.500000,4.0,...,0.0,0.000000,0.000000,0.0,0.0,0.000000,1.152353,0.000000,0.949366,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54713,2.0,17.0,0.500000,1.0,6.0,1.6,2.0,16.0,2.833333,4.0,...,0.0,0.729427,0.000000,0.0,0.0,0.000000,0.000000,1.305865,0.000000,0.000000
54714,5.0,9.0,-0.166667,5.0,4.0,-0.4,1.0,15.0,-0.166667,1.0,...,0.0,0.000000,0.000000,0.0,0.0,0.000000,1.152353,0.000000,0.949366,0.000000
54715,2.0,17.0,-0.333333,1.0,18.0,0.2,1.0,9.0,-0.500000,1.0,...,0.0,0.000000,0.000000,0.0,0.0,0.000000,1.152353,0.000000,0.949366,0.000000
54716,4.0,15.0,0.166667,3.0,9.0,0.4,5.0,17.0,0.166667,3.0,...,0.0,0.729427,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.949366,0.000000
54717,3.0,12.0,0.166667,1.0,10.0,0.0,5.0,13.0,4.833333,1.0,...,0.0,0.000000,0.000000,0.0,0.0,0.939464,0.000000,0.000000,0.949366,0.000000

In [21]:
y

0        Yes
1         No
2        Yes
3        Yes
4        Yes
        ...
54713     No
54714     No
54715     No
54716    Yes
54717     No
Name: voted, Length: 54718, dtype: object

In [22]:
Y

array([[1],
       [0],
       [1],
       ...,
       [0],
       [1],
       [0]])